version: "3.8"
services:
  db:
    image: microsoft/mssql-server-linux:latest
    container_name: orchard-core-db-server
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_backup:/var/opt/mssql/backup
    # https://docs.docker.com/compose/compose-file/#environment
    environment:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/sa_password
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver15#dumpdir
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
      # https://blog.dbi-services.com/managing-sql-server-sa-credentials-with-docker-secrets-on-swarm/
    # Usage of secret file for 'db' service
    secrets:
      - sa_password

# https://docs.docker.com/compose/compose-file/#external
volumes:
  mssql_data:
  mssql_log:
  mssql_backup:

# Define a secret at top level
# External secrets are not available to containers created by docker-compose.
secrets:
  sa_password:
    file: ./sa_password.secret

